'use client';

import { useEffect, useRef, useState } from 'react';

const experiments = [
  { num: '001', title: 'Glass Button', path: '/001' },
  { num: '002', title: 'Liquid Glass', path: '/002' },
  { num: '003', title: 'Experiment 003', path: '/003' },
  { num: '004', title: 'Experiment 004', path: '/004' },
  { num: '005', title: 'Experiment 005', path: '/005' },
  { num: '006', title: 'Experiment 006', path: '/006' },
  { num: '007', title: 'Experiment 007', path: '/007' },
  { num: '008', title: 'Light Card', path: '/008' },
  { num: '009', title: 'Animated Text', path: '/009' },
  { num: '010', title: 'Experiment 010', path: '/010' },
  { num: '011', title: 'ASCII Art', path: '/011' },
  { num: '012', title: 'Chat Interface', path: '/012' },
  { num: '013', title: 'Chat Variant', path: '/013' },
  { num: '014', title: 'Chat Variant', path: '/014' },
  { num: '015', title: 'Shine On Button', path: '/015' },
  { num: '016', title: 'Experiment 016', path: '/016' },
  { num: '017', title: 'Experiment 017', path: '/017' },
  { num: '018', title: 'Experiment 018', path: '/018' },
  { num: '019', title: 'Experiment 019', path: '/019' },
  { num: '020', title: 'Experiment 020', path: '/020' },
  { num: '021', title: 'Reading List', path: '/021' },
  { num: '022', title: 'Loader', path: '/022' },
  { num: '023', title: 'Loader Test', path: '/023' },
  { num: '024', title: 'Experiment 024', path: '/024' },
  { num: '026', title: 'Experiment 026', path: '/026' },
  { num: '027', title: 'Experiment 027', path: '/027' },
  { num: '028', title: 'Experiment 028', path: '/028' },
  { num: '029', title: 'Experiment 029', path: '/029' },
  { num: '030', title: 'Experiment 030', path: '/030' },
  { num: '031', title: 'Agent Loop', path: '/031' },
  { num: '032', title: 'Experiment 032', path: '/032' },
];

export default function Home() {
  const [loadedIframes, setLoadedIframes] = useState<Set<string>>(new Set());
  const observerRef = useRef<IntersectionObserver | null>(null);

  useEffect(() => {
    observerRef.current = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            const expNum = entry.target.getAttribute('data-exp');
            if (expNum && !loadedIframes.has(expNum)) {
              setLoadedIframes((prev) => new Set(prev).add(expNum));
              observerRef.current?.unobserve(entry.target);
            }
          }
        });
      },
      {
        root: null,
        rootMargin: '100px',
        threshold: 0.01,
      }
    );

    return () => observerRef.current?.disconnect();
  }, []);

  useEffect(() => {
    const cards = document.querySelectorAll('.experiment-card-wrapper');
    cards.forEach((card) => {
      if (observerRef.current) {
        observerRef.current.observe(card);
      }
    });
  }, []);

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <div className="w-screen h-screen flex flex-col items-center justify-center flex-shrink-0">
        <div className="h-20 flex items-center justify-center text-gray-600">
          WIP experiment lab (abandon all hope ye who enter here)
        </div>
        <div className="w-full h-full flex items-center justify-center relative overflow-hidden">
          <div className="text-9xl font-mono text-gray-300 tracking-wider">
            EXP
          </div>
        </div>
        <div className="h-20 flex items-center justify-center">
          <a
            href="https://promptcache.com/tools/ascii-art-generator"
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-gray-500 hover:text-gray-700"
          >
            ascii generated by promptcache
          </a>
        </div>
      </div>

      {/* Experiments Section */}
      <section className="w-full max-w-[1400px] px-10 py-20 mx-auto box-border">
        <div className="flex flex-wrap gap-6 w-full justify-center">
          {experiments.map((exp) => (
            <a
              key={exp.num}
              href={exp.path}
              className="group flex-[0_0_calc((100%-48px)/3)] max-w-[400px] min-w-[280px] bg-white border border-gray-200 rounded-xl p-0 no-underline text-inherit transition-all duration-300 relative overflow-hidden cursor-pointer aspect-[16/9] hover:-translate-y-1 hover:shadow-[0_12px_24px_rgba(0,0,0,0.08)] hover:border-gray-300 lg:flex-[0_0_calc((100%-72px)/4)] md:flex-[0_0_calc((100%-24px)/2)] sm:flex-[0_0_100%]"
            >
              <div
                className="experiment-card-wrapper w-full h-full absolute top-0 left-0 overflow-hidden bg-gray-50"
                data-exp={exp.num}
              >
                {loadedIframes.has(exp.num) ? (
                  <iframe
                    src={exp.path}
                    className="w-full h-full border-none block pointer-events-none opacity-0 transition-opacity duration-300 loaded:opacity-100"
                    title={`Experiment ${exp.num}`}
                    onLoad={(e) => {
                      (e.target as HTMLIFrameElement).classList.add('loaded');
                      (e.target as HTMLIFrameElement).style.opacity = '1';
                    }}
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center text-gray-400">
                    {exp.num}
                  </div>
                )}
              </div>
              <div className="absolute top-4 left-4 text-sm font-semibold text-white bg-black/50 px-3 py-1.5 rounded-md tracking-wide z-[2] backdrop-blur-sm">
                {exp.num}
              </div>
            </a>
          ))}
        </div>
      </section>

      <style jsx>{`
        @media (max-width: 1200px) {
          a {
            flex: 0 0 calc((100% - 72px) / 4);
          }
        }
        @media (max-width: 900px) {
          a {
            flex: 0 0 calc((100% - 24px) / 2);
          }
        }
        @media (max-width: 600px) {
          a {
            flex: 0 0 100%;
          }
        }
      `}</style>
    </div>
  );
}
